### ISSUE TITLE
Alternatives to using BOM for data

### ISSUE THREAD

**Issue by adamhsparks** [ropensci-archive/bomrang#144]
Queensland has a proper API that would allow us to access BOM data for point and even gridded data.

* https://www.longpaddock.qld.gov.au/silo/about/overview/
* https://www.longpaddock.qld.gov.au/silo/about/data-products/
* https://www.longpaddock.qld.gov.au/silo/api-documentation/guide/

What say you, @HughParsonage and @jonocarroll? This would allow us to have access to the historical data. Not sure that it provides access to real-time though, so we would lose that functionality.

Should we pursue this capability?

**Comment by DharmaDan** [comment]
Hi @adamhsparks and @jonocarroll. I note that a year has passed since there was discussion here on alternatives, and i am still sorely missing being able to easily use bomrang to pull down historical Wx data from specific BOM (ahem, THE BUREAU) stations. Is there another solution or go-to package now?  Thanks.

**Comment by adamhsparks** [comment]
Unfortunately BOM doesn’t seem interested in supporting any such solutions, so, no. Right now nothing exists yet. The discussed workarounds all have their own drawbacks.

**Comment by DharmaDan** [comment]
:( Oh well, we can live in hope.

Thanks for getting back to me Adam.
